#!/bin/bash
################################################################################
# Downloads and unpacks the Slater-Koster files from dftb.org
################################################################################
scriptdir="$(dirname $0)"
root="$scriptdir/.."
downloaddir="$root/slakos/download"
downloadfile="$root/slakos/DOWNLOAD_SLAKOS"
slakourlprefix="http://www.dftb.org/fileadmin/DFTB/public/slako"

echo "Downloading SLAKO archives:"
for archive in $(cat $downloadfile); do
  tarname=$(basename $archive)
  echo "Downloading archive $archive as $tarname"
  wget -q -O $downloaddir/$tarname $slakourlprefix/$archive
  if [ $? -ne 0 ]; then
    echo "DOWNLOAD FAILED" >&2
  fi
  echo "Unpacking archive $tarname"
  tar -x -C $downloaddir -J -f $downloaddir/$tarname
  if [ $? -ne 0 ]; then
    echo "UNPACKING FAILED" >&2
    exit
  fi
  echo "Removing archive $tarname"
  rm -f $downloaddir/$tarname
done
